// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxsaxjcmotqsfhdwzbdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4c2F4amNtb3Rxc2ZoZHd6YmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzUzOTgsImV4cCI6MjA3MDk1MTM5OH0.0281Vsvo-X3C9z88C9Sq-aWn7OpCbej28YkEwgEiVwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});